[package]
name = "binius-keccak-prove"
version.workspace = true
edition.workspace = true
authors.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
binius-field = { path = "../field" }
binius-math = { path = "../math" }

[dev-dependencies]
rand = { workspace = true, features = ["thread_rng"] }
