[package]
name = "binius-keccak-prove"
version.workspace = true
edition.workspace = true
authors.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
binius-field = { path = "../field" }
binius-math = { path = "../math" }
binius-utils = { path = "../utils" }

[dev-dependencies]
binius-core = { path = "../core" }
binius-prover = { path = "../prover" }
binius-verifier = { path = "../verifier" }
criterion.workspace = true
rand = { workspace = true, features = ["thread_rng"] }

[[bench]]
name = "keccak_ntt"
harness = false
